[package]
authors          = ["qpzm"]
compiler_version = ">=0.36.0"
name             = "chacha_bin"
type             = "bin"
version          = "0.1.0"

[dependencies]
chacha20 = { path = "../chacha20" }
nivc = { path = "../nivc" }